document.write("<p>Informe de la asignatura: ");
document.write(objeto.asignatura);
document.write("</p>");
document.write("<p>Titulación: ");
document.write(objeto.titulacion);
document.write("</p>");
document.write("<p>Centro: ");
document.write(objeto.centro);
document.write("</p>");
document.write("<p>Universidad: ");
document.write(objeto.universidad);
document.write("</p>");
document.write("<p>Curso actual: ");
document.write(objeto.curso);
document.write("</p>");
document.write("<p>Estudiante: ");
document.write(objeto.estudiante);
document.write("</p>");
document.write("<p>e-mail: ");
document.write(objeto.email);
document.write("</p>");